In [4]:
import numpy as np
import torch

from brevitas.nn import QuantHardTanh
from brevitas.nn import QuantReLU

from brevitas.quant import Uint8ActPerTensorFloat

In [2]:
hardtanh = QuantHardTanh(
    act_quant = Uint8ActPerTensorFloat,
    min_val = 0.0,
    max_val = 6.0,
    scaling_impl_type='const',
    bit_width = 4,
    return_quant_tensor=True)

In [3]:
relu6 = QuantReLU(
    min_val = 0.0,
    max_val = 6.0,
    scaling_impl_type='const',
    bit_width = 4,
    return_quant_tensor=True)

In [4]:
inp = (2*np.random.rand(10)-1)*20
inp = torch.tensor(inp)

In [5]:
inp

tensor([-3.4455,  7.0651, -7.7860, -3.2591, 11.9485, -6.1193, 11.3504, 16.5560,
         6.4178, -4.5383], dtype=torch.float64)

In [6]:
oup = hardtanh(inp)
oup

/opt/conda/envs/pytorch_brevitas/lib/python3.10/site-packages/torch/_tensor.py:1362: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at /opt/conda/conda-bld/pytorch_1702400410390/work/c10/core/TensorImpl.h:1900.)
  return super().rename(names)


QuantTensor(value=tensor([0.0000, 6.0000, 0.0000, 0.0000, 6.0000, 0.0000, 6.0000, 6.0000, 6.0000,
        0.0000], dtype=torch.float64), scale=tensor(0.4000), zero_point=tensor(0.), bit_width=tensor(4.), signed_t=tensor(False), training_t=tensor(True))

In [7]:
oup6 = relu6(inp)
oup6

QuantTensor(value=tensor([0.0000, 6.0000, 0.0000, 0.0000, 6.0000, 0.0000, 6.0000, 6.0000, 6.0000,
        0.0000], dtype=torch.float64), scale=tensor(0.4000), zero_point=tensor(0.), bit_width=tensor(4.), signed_t=tensor(False), training_t=tensor(True))

In [1]:
from brevitas.nn import QuantConv2d

In [3]:
def_quant_conv = QuantConv2d(
    in_channels=2, 
    out_channels=4,
    kernel_size=3)

In [8]:
inp = torch.tensor(np.random.rand(2,6,6).astype(np.float32))

In [9]:
oup = def_quant_conv(inp)
print(inp)
print(oup)

tensor([[[0.5230, 0.3968, 0.1809, 0.9967, 0.8929, 0.1067],
         [0.0642, 0.1943, 0.2627, 0.3826, 0.5509, 0.1085],
         [0.7241, 0.0819, 0.3778, 0.2621, 0.2110, 0.9044],
         [0.6931, 0.6280, 0.6630, 0.2137, 0.1219, 0.5346],
         [0.6710, 0.0778, 0.8210, 0.0182, 0.6778, 0.5803],
         [0.9942, 0.4173, 0.3164, 0.8334, 0.6200, 0.7397]],

        [[0.7434, 0.9951, 0.2208, 0.8579, 0.5775, 0.0724],
         [0.0227, 0.5302, 0.9922, 0.7764, 0.2800, 0.2403],
         [0.7006, 0.9120, 0.7960, 0.6701, 0.0508, 0.8320],
         [0.0297, 0.5784, 0.7455, 0.3411, 0.1099, 0.4586],
         [0.4989, 0.1252, 0.6683, 0.7081, 0.7264, 0.0553],
         [0.1136, 0.6803, 0.9187, 0.6888, 0.6260, 0.3467]]])
tensor([[[-0.3010, -0.1033,  0.0329, -0.4914],
         [ 0.0195, -0.0782, -0.0814,  0.0674],
         [-0.1921, -0.4828, -0.2027,  0.0302],
         [ 0.1372, -0.5851, -0.1430,  0.0528]],

        [[-0.0233, -0.1354,  0.0010, -0.2687],
         [-0.1878, -0.0505, -0.2830, -0.1211],
    

In [30]:
# def_quant_conv.quant_weight().scale

# def_quant_conv.weight_quant.tensor_quant.__dict__

# def_quant_conv.quant_weight_scale()

def_quant_conv.weight

Parameter containing:
tensor([[[[-0.1399, -0.2017,  0.2297],
          [-0.0118, -0.1215,  0.1943],
          [ 0.1871, -0.0801, -0.1076]],

         [[-0.2156, -0.1347, -0.0592],
          [ 0.2023, -0.1149,  0.1801],
          [ 0.0598, -0.1651, -0.1067]]],


        [[[ 0.1220, -0.0012,  0.0171],
          [-0.1233,  0.0757,  0.1265],
          [-0.0238, -0.0492, -0.0110]],

         [[-0.1426,  0.0814,  0.1870],
          [-0.0554, -0.2126,  0.0249],
          [ 0.0400,  0.2055, -0.0919]]],


        [[[-0.0126, -0.1591,  0.1477],
          [-0.1599, -0.1904, -0.0049],
          [-0.0672,  0.0719, -0.0909]],

         [[ 0.0801,  0.1035,  0.1093],
          [-0.0531, -0.2036, -0.0541],
          [-0.0865,  0.1808, -0.2024]]],


        [[[ 0.0441, -0.1019,  0.1742],
          [ 0.0461, -0.1119, -0.1186],
          [ 0.0148,  0.0772, -0.1449]],

         [[-0.1314, -0.0784,  0.2130],
          [ 0.2116,  0.2057, -0.1342],
          [-0.0204,  0.0820, -0.1681]]]], requires_grad=True)

In [19]:
def_quant_conv.quant_weight().scale = torch.tensor(np.array(0.19).astype(np.float32))

AttributeError: can't set attribute

In [32]:
def_quant_conv.quant_weight().value

tensor([[[[-0.1393, -0.2008,  0.2297],
          [-0.0127, -0.1212,  0.1935],
          [ 0.1863, -0.0796, -0.1067]],

         [[-0.2152, -0.1338, -0.0597],
          [ 0.2026, -0.1158,  0.1809],
          [ 0.0597, -0.1646, -0.1067]]],


        [[[ 0.1212, -0.0018,  0.0163],
          [-0.1230,  0.0760,  0.1266],
          [-0.0235, -0.0488, -0.0109]],

         [[-0.1429,  0.0814,  0.1863],
          [-0.0561, -0.2134,  0.0253],
          [ 0.0398,  0.2062, -0.0922]]],


        [[[-0.0127, -0.1592,  0.1483],
          [-0.1592, -0.1899, -0.0054],
          [-0.0669,  0.0724, -0.0904]],

         [[ 0.0796,  0.1031,  0.1085],
          [-0.0525, -0.2044, -0.0543],
          [-0.0868,  0.1809, -0.2026]]],


        [[[ 0.0434, -0.1013,  0.1736],
          [ 0.0452, -0.1121, -0.1194],
          [ 0.0145,  0.0778, -0.1447]],

         [[-0.1320, -0.0778,  0.2134],
          [ 0.2116,  0.2062, -0.1338],
          [-0.0199,  0.0814, -0.1682]]]], grad_fn=<MulBackward0>)

In [34]:
import onnx
from onnx import numpy_helper

In [35]:
model = onnx.load('./experiments_brevitas/test_v05_mini_resnet_70k_full_ds/onnx/MY_MBLNET_V2_RESNET_classifier__best_mean_F1__BIPOLAR_Out__QONNX.onnx')

In [41]:
all_in = model.graph.initializer

print(type(all_in))

<class 'google.protobuf.pyext._message.RepeatedCompositeContainer'>


In [54]:
all_in = model.graph.initializer

for idx, inp in enumerate(all_in):
    np_inp = numpy_helper.to_array(inp)
    print(f'{idx}\n{np_inp}')

    print(type(np_inp))
    
    np_idx = np_inp < 1e-5
    print(np_idx)

    print(np_inp.flags)

    new_np_inp = np.copy(np_inp)
    print(new_np_inp.flags)
    # np_inp.setflags(write=1) ### ValueError: cannot set WRITEABLE flag to True of this array
    new_np_inp[np_idx] = 0.

    print(new_np_inp)

    tensor = numpy_helper.from_array(new_np_inp)
    inp.CopyFrom(tensor)
    
    break

0
[5.0170988e-01 1.9045015e-01 2.9435015e-01 2.7288267e-01 2.6639992e-01
 3.4760967e-01 3.4233660e-01 3.1068161e-01 1.3981032e-01 2.7074677e-01
 2.1637638e-01 2.5958401e-01 2.0310082e-01 7.5970888e-01 2.1978000e-01
 2.8921765e-01 2.2940587e-01 4.9129524e-42 3.6184746e-01 3.3086792e-01
 2.1861368e-01 2.7706385e-01 2.7920821e-01 6.9236946e-01 2.5919411e-01
 2.4717720e-01 4.8016509e-01 2.4163520e-01 3.1611204e-01 1.4455533e-01
 1.8094786e-01 1.7973542e-01]
<class 'numpy.ndarray'>
[False False False False False False False False False False False False
 False False False False False  True False False False False False False
 False False False False False False False False]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

[0.5017099  0.19045015 0.29435015 0.27288267 0.26639992 0.34760967
 0.34

In [56]:
all_in = model.graph.initializer

for idx, inp in enumerate(all_in):
    np_inp = numpy_helper.to_array(inp)
    print(f'{idx}\n{np_inp}')

    print(type(np_inp))
    break

0
[0.5017099  0.19045015 0.29435015 0.27288267 0.26639992 0.34760967
 0.3423366  0.3106816  0.13981032 0.27074677 0.21637638 0.259584
 0.20310082 0.7597089  0.21978    0.28921765 0.22940587 0.
 0.36184746 0.33086792 0.21861368 0.27706385 0.2792082  0.69236946
 0.2591941  0.2471772  0.4801651  0.2416352  0.31611204 0.14455533
 0.18094786 0.17973542]
<class 'numpy.ndarray'>


In [57]:
onnx.save_model(model, 'test_onnx_change_weights.onnx')

In [ ]:
# # numpy value which you want to update 
# numpy_array = numpy.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], dtype=float)
# # convert numpy to TensorProto
# tensor = numpy_helper.from_array(numpy_array)
# # copy this TensorProto to target tensor
# model.graph.initializer[0].CopyFrom(tensor)
# print(model.graph.initializer[0])
# // then save the modified model

In [1]:
import numpy as np
import torch

from brevitas.nn import QuantIdentity
from brevitas.core.restrict_val import RestrictValueType

from brevitas.quant import Int8ActPerTensorFloat

In [2]:
a_np = 2*(np.arange(0, 256) / 255) - 1
a_torch = torch.tensor(a_np, dtype=torch.float32)

In [3]:
print(type(a_torch))
print(a_torch.shape)
print(a_torch)

<class 'torch.Tensor'>
torch.Size([256])
tensor([-1.0000, -0.9922, -0.9843, -0.9765, -0.9686, -0.9608, -0.9529, -0.9451,
        -0.9373, -0.9294, -0.9216, -0.9137, -0.9059, -0.8980, -0.8902, -0.8824,
        -0.8745, -0.8667, -0.8588, -0.8510, -0.8431, -0.8353, -0.8275, -0.8196,
        -0.8118, -0.8039, -0.7961, -0.7882, -0.7804, -0.7725, -0.7647, -0.7569,
        -0.7490, -0.7412, -0.7333, -0.7255, -0.7176, -0.7098, -0.7020, -0.6941,
        -0.6863, -0.6784, -0.6706, -0.6627, -0.6549, -0.6471, -0.6392, -0.6314,
        -0.6235, -0.6157, -0.6078, -0.6000, -0.5922, -0.5843, -0.5765, -0.5686,
        -0.5608, -0.5529, -0.5451, -0.5373, -0.5294, -0.5216, -0.5137, -0.5059,
        -0.4980, -0.4902, -0.4824, -0.4745, -0.4667, -0.4588, -0.4510, -0.4431,
        -0.4353, -0.4275, -0.4196, -0.4118, -0.4039, -0.3961, -0.3882, -0.3804,
        -0.3725, -0.3647, -0.3569, -0.3490, -0.3412, -0.3333, -0.3255, -0.3176,
        -0.3098, -0.3020, -0.2941, -0.2863, -0.2784, -0.2706, -0.2627, -0.2549,

In [4]:
quant_id_layer = QuantIdentity(
    bit_width = 4,
    min_val = -1,
    max_val = 1 - 2 ** (-3),
    narrow_range = False, 
    restrict_scaling_type = RestrictValueType.POWER_OF_TWO,
    return_quant_tensor = True)

In [7]:
quant_oup = quant_id_layer(a_torch)

/opt/conda/envs/pytorch_brevitas/lib/python3.10/site-packages/torch/_tensor.py:1362: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at /opt/conda/conda-bld/pytorch_1702400410390/work/c10/core/TensorImpl.h:1900.)
  return super().rename(names)


In [8]:
quant_oup

QuantTensor(value=tensor([-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000,
        -0.8750, -0.8750, -0.8750, -0.8750, -0.8750, -0.8750, -0.8750, -0.8750,
        -0.8750, -0.8750, -0.8750, -0.8750, -0.8750, -0.8750, -0.8750, -0.8750,
        -0.7500, -0.7500, -0.7500, -0.7500, -0.7500, -0.7500, -0.7500, -0.7500,
        -0.7500, -0.7500, -0.7500, -0.7500, -0.7500, -0.7500, -0.7500, -0.7500,
        -0.6250, -0.6250, -0.6250, -0.6250, -0.6250, -0.6250, -0.6250, -0.6250,
        -0.6250, -0.6250, -0.6250, -0.6250, -0.6250, -0.6250, -0.6250, -0.6250,
        -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000,
        -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000,
        -0.3750, -0.3750, -0.3750, -0.3750, -0.3750, -0.3750, -0.3750, -0.3750,
        -0.3750, -0.3750, -0.3750, -0.3750, -0.3750, -0.3750, -0.3750, -0.3750,
        -0.2500, -0.2500, -0.2500, -0.2500, -0.2500, -0.2500, -0.2500, -0.2500,
        -0.2500, -0.25